disabled_rules:
- trailing_whitespace
- colon
- comma
- control_statement
- vertical_whitespace
- switch_case_alignment
- opening_brace
- comment_spacing
- trailing_newline
- unneeded_break_in_switch

opt_in_rules:
- empty_count
- empty_string
- fatal_error_message
- force_unwrapping
- implicitly_unwrapped_optional
- yoda_condition

included:
- WeatherAround

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
- WeatherAround/UIColorExtension.swift

force_cast: warning

line_length:
    warning: 260
    error: 350

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8


cyclomatic_complexity:
    warning: 15
    error: 25

reporter: "xcode"
